[package]
name = "gfa2bin-aligner"
version = "0.0.3"
edition = "2024"

[dependencies]
clap = "4.5.45"
rayon = { version = "1.11.0", optional = true }
gfa-reader = {git = "https://github.com/MoinSebi/gfa-reader"}
flate2 = "1.0.23"
log = "0.4.14"

[features]
default = ["rayon"]
rayon = ["dep:rayon"]